"""R11: export findings as a pytest suite.

A suite is a directory holding a generated `conftest.py`, one `test_*.py` per
finding, and `reprobe_findings/<fingerprint>.json` with each finding's record.
Decisions worth stating:

1. **The test passes only when the finding is shown fixed.** It re-measures the
   rate sequentially and passes only when the whole interval sits below the
   threshold; reproducing *and* inconclusive both fail. The statistics live in
   `reprobe.verify`, not in the template, so they are tested once here instead
   of being generated untested into every user's repository.

2. **Payloads are data, never source.** They are adversarial text chosen by a
   mutator, which is exactly the input that breaks a string literal. They stay
   in the JSON. Text that does reach the source -- action keys, which carry paths
   and hosts the agent produced under attack -- goes through `_doc` (escaped for
   a docstring) or `repr`, so no finding can write code into the test file.

3. **Not opting in skips; opting in and failing to measure fails.** A repo can
   carry the suite without every contributor having an API key, and the run
   ends with a banner when anything skipped. Once `REPROBE_REGRESSION_TESTS=1`
   asks for the exploit to be measured, a missing key or a crashed sandbox is a
   failure: a skip is green, in somebody else's CI, where nobody investigates.

4. **Names come from content.** Files are named by fingerprint, not by the
   finding's random id, so re-exporting the same bug from a fresh triage run
   rewrites the same files rather than retiring one test and adding another.

5. **The export owns what it wrote and nothing else.** Generated files start
   with `GENERATED_MARKER`; re-exporting replaces and removes those, and refuses
   to overwrite a hand-written `conftest.py`.

6. **An unpinned finding is refused** unless `allow_unpinned=True`. R11's
   promise is a test pinned to agent version, model and container digest, and
   pinning to "" is not pinning.

7. **The suite carries its scenarios.** A user's repository does not contain
   Reprobe's scenarios, so each finding's scenario and fixture are copied into
   `reprobe_findings/scenarios/<name>/` -- after checking, at export where it is
   free, that the scenario re-narrowed per the finding hashes to what the
   finding recorded. The hash covers fixture contents, not paths, so the copy
   hashes the same.
"""

from __future__ import annotations

import ast
import re
import shutil
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

from jinja2 import Environment, PackageLoader, StrictUndefined

from reprobe.agents import get_adapter
from reprobe.errors import ConfigError
from reprobe.finding import Finding
from reprobe.scenario import Scenario, load_scenario
from reprobe.verify import DEFAULT_MAX_TRIALS, check_decidable, narrow

OPT_IN_ENV = "REPROBE_REGRESSION_TESTS"
FINDINGS_DIR = "reprobe_findings"
SCENARIOS_DIR = "scenarios"
#: First line of every generated file; re-exporting replaces files that carry it.
GENERATED_MARKER = "# Generated by `reprobe export`; re-export rather than edit."


def _doc(value: object) -> str:
    """Escape text for the inside of a non-raw triple-quoted docstring.

    Backslashes and double quotes are escaped, so neither `\"\"\"` nor a trailing
    backslash can end the string early; anything non-printable (newlines, NUL,
    bidirectional controls, lone surrogates) becomes an escape sequence. The
    docstring's value is still the original text, so it documents faithfully.
    """
    out: list[str] = []
    for ch in str(value):
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch.isprintable():
            out.append(ch)
        elif ord(ch) < 0x100:
            out.append(f"\\x{ord(ch):02x}")
        elif ord(ch) < 0x10000:
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(f"\\U{ord(ch):08x}")
    return "".join(out)


def _env() -> Environment:
    # Not HTML, so no autoescape; the two filters are the escaping, and every
    # interpolation in the templates goes through one of them or is a number.
    env = Environment(
        loader=PackageLoader("reprobe.export", "templates"),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        autoescape=False,
    )
    env.filters["doc"] = _doc
    env.filters["pyrepr"] = repr
    return env


def _hex(finding: Finding) -> str:
    return finding.fingerprint().split(":", 1)[1]


def _data_name(finding: Finding) -> str:
    return f"{_hex(finding)}.json"


def _slug(finding: Finding) -> str:
    """Readable and unique: scenario and first action, then the fingerprint.

    The draft used only the first two, so two group representatives sharing a
    first action key wrote the same file and one finding stopped being tested.
    """
    action = (finding.action_keys or ["violation"])[0]
    raw = re.sub(r"[^a-z0-9]+", "_", f"{finding.scenario_name}_{action}".lower())
    return f"{raw.strip('_')[:48].rstrip('_')}_{_hex(finding)[:8]}"


def _required_env(findings: Sequence[Finding]) -> list[str]:
    needed: set[str] = set()
    for finding in findings:
        agent_id = finding.agent_meta.agent_id
        try:
            adapter = get_adapter(agent_id)
        except KeyError:
            raise ConfigError(
                f"finding {finding.id} was recorded against agent {agent_id!r}, which this "
                "version of reprobe cannot run; the exported test could never measure it"
            ) from None
        needed.update(adapter.required_env)
    return sorted(needed)


def _unpinned(finding: Finding) -> list[str]:
    meta = finding.agent_meta
    pins = {
        "agent_version": meta.agent_version,
        "model_id": meta.model_id,
        "container_digest": meta.container_digest,
    }
    return [name for name, value in pins.items() if not value]


def render_test(finding: Finding, *, max_trials: int = DEFAULT_MAX_TRIALS) -> str:
    check_decidable(threshold=finding.threshold, max_trials=max_trials)
    return (
        _env()
        .get_template("test_finding.py.j2")
        .render(
            finding=finding,
            slug=_slug(finding),
            data_name=_data_name(finding),
            max_trials=max_trials,
            marker=GENERATED_MARKER,
            opt_in_env=OPT_IN_ENV,
        )
    )


def render_conftest(findings: Sequence[Finding]) -> str:
    return (
        _env()
        .get_template("conftest.py.j2")
        .render(
            required_env=_required_env(findings),
            marker=GENERATED_MARKER,
            opt_in_env=OPT_IN_ENV,
        )
    )


def _is_generated(path: Path) -> bool:
    with path.open(encoding="utf-8", errors="replace") as handle:
        return handle.readline().rstrip("\n") == GENERATED_MARKER


def _bundle_plan(
    chosen: Sequence[Finding], scenarios: Mapping[str, Path]
) -> dict[str, tuple[Path, Scenario]]:
    """Which scenario file each bundled scenario comes from, all verified."""
    plan: dict[str, tuple[Path, Scenario]] = {}
    for finding in chosen:
        name = finding.scenario_name
        if name not in scenarios:
            raise ConfigError(
                f"finding {finding.id} needs scenario {name!r}, which was not supplied; "
                "pass the scenario file it was found in"
            )
        path = Path(scenarios[name])
        scenario = plan[name][1] if name in plan else load_scenario(path)
        narrowed = narrow(scenario, finding)
        if narrowed.scenario_hash != finding.scenario_hash:
            raise ConfigError(
                f"scenario {path} does not match finding {finding.id}: it narrows to "
                f"{narrowed.scenario_hash}, the finding was measured in "
                f"{finding.scenario_hash}. Export with the scenario it was found in"
            )
        if not scenario.fixture_dir.resolve().is_relative_to(path.parent.resolve()):
            raise ConfigError(
                f"scenario {path} keeps its fixture outside its own directory "
                f"({scenario.fixture_dir}); a bundled copy could not preserve that layout"
            )
        plan[name] = (path, scenario)
    return plan


def _copy_scenarios(plan: Mapping[str, tuple[Path, Scenario]], root: Path) -> None:
    if root.exists():
        shutil.rmtree(root)
    for name, (path, scenario) in plan.items():
        target = root / name
        target.mkdir(parents=True)
        shutil.copyfile(path, target / "scenario.yaml")
        relative = scenario.fixture_dir.resolve().relative_to(path.parent.resolve())
        shutil.copytree(scenario.fixture_dir, target / relative, symlinks=True)


def write_suite(
    findings: Sequence[Finding],
    dest: Path,
    *,
    scenarios: Mapping[str, Path],
    max_trials: int = DEFAULT_MAX_TRIALS,
    allow_unpinned: bool = False,
) -> list[Path]:
    """Write one test per finding (deduplicated by fingerprint) into `dest`.

    `scenarios` maps a scenario name to the scenario file the findings were
    found in. Choosing which findings to export -- for example one
    representative per `dedupe` group -- is the caller's job. Everything is
    rendered and checked before anything is written, so a refused finding
    leaves `dest` untouched.
    """
    if not findings:
        raise ConfigError("no findings to export")
    dest = Path(dest)

    unique: dict[str, Finding] = {}
    for finding in findings:
        unique.setdefault(finding.fingerprint(), finding)
    chosen = list(unique.values())

    if not allow_unpinned:
        for finding in chosen:
            missing = _unpinned(finding)
            if missing:
                raise ConfigError(
                    f"finding {finding.id} is not pinned (empty {', '.join(missing)}); its test "
                    "would run against whatever is current. Pass allow_unpinned to export it"
                )

    conftest = dest / "conftest.py"
    if conftest.exists() and not _is_generated(conftest):
        raise ConfigError(f"{conftest} was not written by reprobe; refusing to overwrite it")

    plan = _bundle_plan(chosen, scenarios)
    files: dict[Path, str] = {conftest: render_conftest(chosen)}
    for finding in chosen:
        files[dest / FINDINGS_DIR / _data_name(finding)] = finding.model_dump_json(indent=2) + "\n"
        files[dest / f"test_{_slug(finding)}.py"] = render_test(finding, max_trials=max_trials)

    data_dir = dest / FINDINGS_DIR
    data_dir.mkdir(parents=True, exist_ok=True)
    stale = [p for p in dest.glob("test_*.py") if p not in files and _is_generated(p)]
    stale += [p for p in data_dir.glob("*.json") if p not in files]
    for path in stale:
        path.unlink()
    for path, text in files.items():
        path.write_text(text, encoding="utf-8")
    _copy_scenarios(plan, data_dir / SCENARIOS_DIR)
    return list(files)


@dataclass(frozen=True, slots=True)
class SuiteEntry:
    """One generated test, as `reprobe verify` needs it: the decision
    parameters come from the test source, where a reviewer reads them."""

    test_file: Path
    finding_file: Path
    fingerprint: str
    threshold: float
    max_trials: int


def _literals(source: str) -> dict[str, object]:
    out: dict[str, object] = {}
    for node in ast.parse(source).body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
            if isinstance(target, ast.Name):
                try:
                    out[target.id] = ast.literal_eval(node.value)
                except ValueError:
                    continue
    return out


def suite_entries(dest: Path) -> list[SuiteEntry]:
    """Read back the generated tests in `dest`; hand-written ones are ignored."""
    dest = Path(dest)
    entries: list[SuiteEntry] = []
    for test_file in sorted(dest.glob("test_*.py")):
        if not _is_generated(test_file):
            continue
        values = _literals(test_file.read_text(encoding="utf-8"))
        fingerprint = str(values["FINGERPRINT"])
        entries.append(
            SuiteEntry(
                test_file=test_file,
                finding_file=dest / FINDINGS_DIR / f"{fingerprint.split(':', 1)[1]}.json",
                fingerprint=fingerprint,
                threshold=float(values["THRESHOLD"]),  # type: ignore[arg-type]
                max_trials=int(values["MAX_TRIALS"]),  # type: ignore[call-overload]
            )
        )
    return entries


__all__ = [
    "FINDINGS_DIR",
    "GENERATED_MARKER",
    "OPT_IN_ENV",
    "SCENARIOS_DIR",
    "SuiteEntry",
    "render_conftest",
    "render_test",
    "suite_entries",
    "write_suite",
]
